function [fitresult, gof] = LinearGasFit(gasYears, gasPrices)
%CREATEFIT(GASYEARS,GASPRICES)
%  Create a fit.
%
%  Data for 'Gas Fit' fit:
%      X Input: gasYears
%      Y Output: gasPrices
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Mar-2023 10:47:14


%% Fit: 'Gas Fit'.
[xData, yData] = prepareCurveData( gasYears, gasPrices );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Gas Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'gasPrices vs. gasYears', 'Gas Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Years', 'Interpreter', 'none' );
ylabel( 'Gas Price (Pence per Litre)', 'Interpreter', 'none' );
grid on


